config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  root 'home#index'

  resource :user
  resource :health_profile
  resources :exercises, only: [:index]
  resources :foods
  # resources :food_searches 
  resources :workouts, only: [:create, :destroy]
  resources :pending_workouts, only: [:create]
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :mets, presence: true
  has_many :workouts

  def burn_time(calories, weight) #model gets cal and weight from the view
    burn_time_calculator = BurnTimeCalculator.new(calories, weight, mets)
    burn_time_calculator.burn_time
  end

  def self.some
    where(name:["Walk - moderate", "Run - 10 min/mi", 
                "Cycling - moderate",
                "Swim - easy", "Standing"])
  end
end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, :calories, presence: true

  def self.search_by_name(food)
    Food.where("name ilike ?", "%#{food}%")
  end
end

app/models/pending_workout.rb
class PendingWorkout
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_workout(exercise_id, calories, food_search)
    contents["workout"] = { "exercise_id" => exercise_id, 
                            "calories"    => calories, 
                            "food_search" => food_search 
                          }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :nickname, :token, presence: true, uniqueness: true

  has_many :workouts

  def self.find_or_create_from_auth(data)
    user = User.find_or_create_by(provider: data.provider, uid: data.uid)
    user.nickname   = data.info.nickname
    user.image_url  = data.info.image
    user.token      = data.credentials.token
    
    user.save!

    user
  end

  def first_time?
    age.nil?
  end

  def missing_weight?
    weight.nil?
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :exercise_id, presence: true
  validates :calories, presence: true
  validates :food_search, presence: true

  belongs_to :user
  belongs_to :exercise

  def burn_time
    exercise.burn_time(calories, user.weight) 
  end

  def self.desc_sorted
    order(:created_at => :desc)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize!
    redirect_to root_path unless current_user  
  end

  def pending_workout
    @pending_workout ||= PendingWorkout.new(session[:pending_workout])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

  def index
      @workout = Workout.new
      @food_search, @calories = params[:food_search].first.match(/(.+) \|.+\: (.+)/).captures
      @calories = @calories.to_i

      if current_user
        @weight = current_user.weight
      else
        @weight = params[:weight].to_i
      end

    if current_user.nil?
      @exercises = Exercise.some
    else
      @exercises = Exercise.all
    end
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    respond_to do |format|
      format.json do
        foods = Food.search_by_name(params[:food_search]).map do |food|
          {
            name: food.name,
            calories: food.calories 
          }
        end
        render json: foods
      end
    end
  end
end

app/controllers/health_profiles_controller.rb
class HealthProfilesController < ApplicationController

  def edit
    @body_class="registration-image"
  end
  
  def index
  end

  def update
    if current_user.update_attributes(user_health_params) && current_user.missing_weight?
      redirect_to edit_health_profile_path
    else
      redirect_to user_path
      flash[:notice] = "Profile Complete!"
    end
  end

  private

  def user_health_params
    params.require(:user).permit(:first_name, :last_name, :email, :gender, :age, 
          :weight, :fitness_level)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @body_class="home-pg-image"
  end


end

app/controllers/pending_workouts_controller.rb
class PendingWorkoutsController < ApplicationController

  def create
    exercise_id = params["workout"]["exercise_id"]
    calories    = params["workout"]["calories"]
    food_search = params["workout"]["food_search"]
    pending_workout.add_workout(exercise_id, calories, food_search)
    session[:pending_workout] = pending_workout.contents
    flash[:success] = "Login with Twitter to save your workout."
    redirect_to '/auth/twitter' 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id

    if !user
      flash[:error] = "sorry there was an errore with twitter"
      redirect_to root_path and return
    end

    if pending_workout.contents.present?
      user.workouts.create(pending_workout.contents["workout"])
      session[:pending_workout].clear
    end

    if user.first_time? 
      redirect_to edit_user_path
      flash[:success] = "Welcome #{current_user.nickname}! Please fill out this information."
    else
      redirect_to user_path
      flash[:success] = "Welcome back!"
    end
  end

  def destroy
    session.clear
    redirect_to root_path
    flash[:danger] = "Successfully logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @body_class="user-show-image"
  end

  def show
    @body_class="user-show-image"

    if current_user 
      @workouts = current_user.workouts.desc_sorted
    else
      redirect_to root_path
      flash[:notice] = "You are not logged in."
    end
  end

  def update
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def create
    if current_user 
      workout = Workout.create(workout_params.merge(user_id: current_user.id, exercise_id: params["workout"]["exercise_id"]))
      
      workout.save!
      
      redirect_to user_path
      flash[:notice] = "Workout saved!"
    else 
      redirect_to '/auth/twitter' 
    end
  end

  def destroy
    workout = current_user.workouts.find(params[:id])
    workout.destroy
    redirect_to user_path
    flash[:danger] = "Workout deleted!"
  end

  private
  def workout_params
    params.require(:workout).permit(:exercise_id,
                    :calories, :food_search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pending_workouts_helper.rb
module PendingWorkoutsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/index.html.erb
<div class="container">
 <div class="row">
    <div class="col-xs-10">
    <div>
      <h1> <%= @food_search %> sounds delicious! </h1>
      <h3> That's <em>only</em> <%= @calories %> calories!</h3>
      <h4> Since you weigh <%= @weight %>  pounds, here are some ways to earn that splurge!</h4>
    </div>

  <div class="col-xs-8">

  <% path = current_user ? workouts_path : pending_workouts_path%>
  <%= form_tag path do %>
    <table class="table table-condensed small-text">
      <tr>
        <th></th>
        <th>Exercise</th>
        <th class="centered">Time to Burn it Off</th>
      </tr>

      <% @exercises.each do |exercise| %>
        <tr class="" border ="1">
          <td ><%= radio_button_tag "workout[exercise_id]", exercise.id, false, :checked => (exercise == @exercises.first)  %></td>
          <td> <%= label_tag "workout_exercise_id_#{exercise.id}", exercise.name %></td>
          <td class="centered"> <%= exercise.burn_time(@calories, @weight) %></td>
        </tr>
      <% end %>
    </table>
    <%= hidden_field_tag 'workout[calories]', @calories %>
    <%= hidden_field_tag 'workout[food_search]', @food_search %>
    <p> <%= submit_tag 'Save it!', class: "btn btn-success white-text" %> <em>(click here to save your workout!)</em></p>
  <% end %>
 
  </div>

    <div class="col-xs-4 pull-right">
      <%= image_tag('WILL-RUN-FOR-FOOD_right.png') %>
    </div>

    </div>  
  </div>
</div>

app/views/health_profiles/_activity_level_data.html.erb
  <hr>
  <h3>How fit are you? </h3>

  <div>
    <%= f.label(:fitness_level_sedentary) do %>
      <span class="pad-right2"><%= f.radio_button(:fitness_level, "1: Sedentary") %></span>
      <strong> Sedentary: You've heard of exercise </strong>
    <% end %> 
  </div><br>

  <div>
    <%= f.label(:fitness_level_somewhat_ative) do %>
      <span class="pad-right2"><%= f.radio_button(:fitness_level, "2: Somewhat Fit") %></span>
      <strong> Somewhat Fit: You participate in light exercise or take long walks </strong>
    <% end %> 
  </div><br>
 
  <div>
    <%= f.label(:fitness_level_moderately_fit) do %>
      <span class="pad-right2"><%= f.radio_button(:fitness_level, "3: Moderate") %></span>
      <strong> Moderate: You exercise 2-3 times a week and push yourself pretty hard </strong>
    <% end %> 
  </div><br>
  
  <div>
    <%= f.label(:fitness_level_crazy_fit) do %>
      <span class="pad-right2"><%= f.radio_button(:fitness_level, "4: Diesel Fit") %></span>
      <strong> Diesel Fit: You participate in physical sports such as jogging or mountain-biking daily</strong>
    <% end %> 
  </div><br>

app/views/health_profiles/edit.html.erb
<div class="container">
<div class="col-md-8">
  <div class="form-area">  

    <h1><%= current_user.nickname %>'s Health Profile</h1>
    <%= form_for(current_user, url: health_profile_path, method: :patch, role:"form") do |f| %>

      <div class="col-md-12">
        <span class="pad-right"><strong> Gender </strong></span>
          <%= f.label(:gender_female, "Female") %>
          <span class="pad-right"><%= f.radio_button(:gender, "female") %></span>

          <%= f.label(:gender_male, "Male") %>   
         <span class="pad-right"><%= f.radio_button(:gender, "male") %></span>
      </div>

      <div class="form col-md-4" >
        <%= f.label(:age, "Age") %>   
        <%= f.number_field(:age, in: 1.0..100.0, step: 1.0, class: "form-control") %>
      </div>

      <div class="form col-md-4" >
        <%= f.label(:weight, "Weight (lbs)") %> 
        <%= f.number_field(:weight, in: 80..400.0, step: 1.0, min: 50, class: "form-control", required: true) %>
      </div><br>

      <div class="col-md-12">
        <%= render partial: "health_profiles/activity_level_data", locals: { f: f} %>
      </div>

    <div class="row">
      <div class="col-md-4 pad-left">
        <%= f.submit "Submit", class: "btn btn-info" %>
      </div>
    </div>
    <% end %>
  </div>
  </div>

app/views/home/_food_search_home.html.erb
<div class="column-xs-8">
  <%= form_tag(exercises_path, method: :get)  do %>

    <p>
      <%= text_field(:food_search, nil, autocomplete: "off", 
                      placeholder: "search for food", class: "form-control black-text typehead centered tt-dropdown-menu", id: "scrollable-dropdown-menu", required: true) %>
    </p>
    <% if current_user.nil? %>
    <p>
      <%= number_field_tag(:weight, nil, placeholder: "enter weight", min: 50, class: "form-control black-text", required: true) %>
    </p>
    <% end %>
    <p class="centered">
      <%= submit_tag 'EARN IT NOW!', class: 'btn btn-success', id: "find-food", disabled: true %>
    </p>

  <% end %>
</div>

app/views/home/index.html.erb
<div>
  <div class="row">

    <div class="col-xs-7 center" >
      <div class="center" id="app-explanation">
      <h1> Burn it to Earn It </h1>
        <h3> You want a juicy burger but you're concerned about the number of calories? Go ahead and eat it! Search for a food and enter your weight. We'll tell you <em><br>HOW to BURN IT OFF!</em>
        </h3>
        <br>
        <div class='col-xs-6'>
          <%= render 'food_search_home' %>
        </div>
      </div>
    </div>
  </div>
  
</div>

app/views/layouts/_black_nav_bar.html.erb
<nav class="navbar nav-black-margin ">
  <ul class="nav navbar-nav navbar-right">
    <%= render 'layouts/common_navbar' %>
  </ul>
</nav>

app/views/layouts/_common_navbar.html.erb
<li><%= link_to "Home", root_path %></li>
<% if current_user %>
  <li class="twitter-name-correction">Welcome <%= current_user.nickname %></li>
  <% if current_user.image_url.present? %>
  <li><%= image_tag(current_user.image_url, class: "img-circle img-thumbnail")%></li>
  <% end %>
  <li><%= link_to "My Account", user_path %></li>
  <li class="nav-right "> <%= link_to "Logout", logout_path %></li>
<% else %>
  <li><%= link_to image_tag("sign-in-with-twitter-gray.png"), '/auth/twitter' %> </li>
<% end %>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar nav-main" role="banner" >
      <!-- Brand and toggle get grouped for better mobile display -->
      
  <div class="nav-margin">
    <% if current_page?('/') %>
      <%= render 'layouts/transparent_navbar' %>
    <% else %>
      <%= render 'layouts/black_nav_bar' %>
    <% end %>
  </div>
</nav>

app/views/layouts/_transparent_navbar.html.erb
<nav class="navbar navbar-transparent">
  <ul class="nav navbar-nav navbar-right">
    <%= render 'layouts/common_navbar' %>
  </ul>
</nav>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Burn It To Earn It</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/nav_bar' %>
  <body class="opacity <%=@body_class%>">
      <div class="flash">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{name} text-center" %>
        <% end %>
      </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user/new_html.erb
<div class="form">
  <h1>Sign Up</h1>

    <%= form_for(:user, url: users_path, method: :post, role:"form") do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>

    <%= f.label :display_name %>
    <%= f.text_field :display_name, class: "form-control" %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.submit "Create Account", id: "check-in", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/_food_search_user.html.erb
  <%= form_tag(exercises_path, method: :get)  do %>

      <div class="search-box form-inline">
        <%= text_field(:food_search, nil, autocomplete: "off", 
                        placeholder: "search for food", class: "form-control black-text typehead centered tt-dropdown-menu", id: "scrollable-dropdown-menu", required: true) %>
      <!-- </div> -->

      <!-- <div class="col-xs-4 center-in-div"> -->
        <%= submit_tag 'EARN IT NOW!', class: 'btn btn-success', id: "find-food", disabled: true %>
    </div>

  <% end %>

app/views/users/edit.html.erb
<div class="form col-xs-6 table-margin">
  <h1><%= current_user.nickname %>'s Info</h1>

  <%= form_for(current_user, url: health_profile_path, method: :patch, role:"form") do |f| %>

  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: "form-control" %>
  </div><br>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div><br>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div><br>

  <%= f.submit "Submit", id: "check-in", class: "btn btn-primary" %>    
  <% end %>
</div>

app/views/users/show.html.erb
  <div class="row">
    <div class="col-xs-12">


      <div class="col-xs-3 centered pad-top" id="edit">
        <%= image_tag(current_user.image_url, class: "img-circle img-thumbnail user-image") %>
        <h4><em> <%= current_user.nickname %></em></h4>
        <hr>
        <strong>Age</strong><br>
        <p><%= current_user.age %></p>

         <strong>Weight</strong><br>
        <p><%= current_user.weight %></p>
        
        <strong>Fitness Level</strong> 
        <p><%= current_user.fitness_level%></p>
        <p class="word-link"><%= link_to "Edit profile", edit_user_path %></p>
        <p><span class="word-link"> <%= link_to "Edit Health profile", edit_health_profile_path %></span></p>
      </div>

      <div class='col-xs-9'>
        <div class="centered pad-top">
          <% if current_user && !current_user.first_name.present? %>
            <h1> <%= current_user.nickname %>'s Dashboard </h1>
          <% else %>
            <h1> <%= current_user.first_name %>'s Dashboard </h1>
          <% end %>
         <%= render :partial => 'food_search_user' %>
        </div>
      </div>

      <div class='col-xs-9'>
      <h2> My Scheduled Workouts</h2>
      <table class="table table-condensed">
      <tr>
        <th>Splurge Food</th>
        <th class="centered">Calories</th>
        <th class="centered">Exercise</th>
        <th class="centered">Burn Time</th>
        <th></th>
      </tr>

      <% @workouts.each do |workout| %>
        <tr class="" border ="1">
          <td> <%= truncate(workout.food_search, length: 50)%></td>
          <td class="centered"> <%= workout.calories %></td>
          <td class="centered"> <%= workout.exercise.name %></td>
          <td class="centered"> <%= workout.burn_time %></td>
          <td> <span class="word-link"> <%= link_to 'Delete', workout_path(workout), method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
        </tr>
      <% end %>
    </table>
   
      <hr>
      </div>

    </div>